version: '3'

vars:
  VENV: .venv
  PYTHON_BIN: '{{.VENV}}/bin/python'
  PIP_BIN: '{{.VENV}}/bin/pip'
  PYTEST_BIN: '{{.VENV}}/bin/pytest'
  RUFF_BIN: '{{.VENV}}/bin/ruff'
  MYPY_BIN: '{{.VENV}}/bin/mypy'

tasks:
  ensure-venv:
    desc: Create the local virtualenv if missing.
    status:
      - test -x {{.PYTHON_BIN}}
    cmds:
      - python -m venv {{.VENV}}

  install:
    desc: Mirror the README install snippet to entangle docs with reality.
    deps: [docs:tangle]
    cmds:
      - '{{.PIP_BIN}} install -e ".[dev]"'
      - '{{.PYTEST_BIN}}'

  lint:
    desc: Run Ruff over source and tests.
    deps: [docs:tangle]
    cmds:
      - '{{.RUFF_BIN}} check src tests'

  typecheck:
    desc: Run mypy over the library sources.
    deps: [docs:tangle]
    cmds:
      - '{{.MYPY_BIN}} src'

  test:
    desc: Run the pytest suite.
    deps: [docs:tangle]
    cmds:
      - '{{.PYTEST_BIN}}'

  qa:
    desc: Run the standard lint -> typecheck -> test chain.
    deps: [lint, typecheck, test]

  docs:verify-install:
    desc: Assert README install block matches the automated steps.
    silent: true
    cmds:
      - grep -F "python -m venv .venv" README.md >/dev/null
      - grep -F 'pip install -e ".[dev]"' README.md >/dev/null
      - grep -F "pytest" README.md >/dev/null

  docs:tangle:
    desc: Regenerate source files from literate documentation.
    deps: [ensure-venv]
    cmds:
      - |
        {{.PYTHON_BIN}} - <<'PY'
        import pathlib, re

        doc = pathlib.Path("docs/tools.md")
        text = doc.read_text()
        match = re.search(r"```python file=([^\n]+)\n(.*?)```", text, re.S)
        if not match:
            raise SystemExit("Unable to find tools/tangle_docs.py block in docs/tools.md")

        target = pathlib.Path(match.group(1))
        code = match.group(2).rstrip() + "\n"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code)
        PY
      - '{{.PYTHON_BIN}} tools/tangle_docs.py docs/service_impl.md docs/library.md docs/service.md docs/tools.md'

  clean:
    desc: Remove generated artifacts (src/, tests/, tools/) so tangling can rebuild them.
    cmds:
      - rm -rf src tests tools

  build:
    desc: Clean generated artifacts and rebuild them from docs in one go.
    cmds:
      - task clean
      - task docs:tangle

  activate:
    desc: Spawn an interactive shell with the virtualenv activated.
    deps: [ensure-venv]
    interactive: true
    cmds:
      - |
        bash -lc 'exec bash --rcfile <(cat <<'"'"'TASKRC'"'"'
        if [ -f "$HOME/.bashrc" ]; then source "$HOME/.bashrc"; fi
        export VIRTUAL_ENV_DISABLE_PROMPT=1
        source {{.VENV}}/bin/activate
        PS1="(.venv C-d to deactivate) $PS1"
        TASKRC
        ) -i'
